test:
  image: thelurps/pandoc:testing
  script:
    - make all
  variables:
    VERSION: $CI_COMMIT_SHA 
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "README-$VERSION.pdf"
