name: Build and test

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thelurps/pandoc:${{github.ref.name}}
  test:
    needs: build
    runs-on: ubuntu-latest
    container: thelurps/pandoc:testing
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: pandoc README.md -o README.pdf
      - uses: actions/upload-artifact@master
        with:
          path: README.pdf
