name: Build and test

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thelurps/pandoc:${{github.ref_name}}
  test:
    needs: build
    runs-on: ubuntu-latest
    container: thelurps/pandoc:${{github.ref_name}}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          git config --global --add safe.directory /__w/docker-pandoc/docker-pandoc
          pandoc metadata.yml README.md \
            --template=./pandoc-latex-template/eisvogel.tex \
            --listings \
            --output=README-$(git describe --tags --dirty --always).pdf
      - uses: actions/upload-artifact@master
        with:
          path: 'README-*.pdf'
