name: Build and test dev

on:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thelurps/pandoc
          tags: testing
  test:
    needs: build
    runs-on: ubuntu-latest
    container: thelurps/pandoc:testing
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: pandoc README.md -o README.pdf
      - uses: actions/upload-artifact@master
        with:
          path: README.pdf
