name: Release

on:
  push:
    branches:
      - 'latest'
      - 'testing'
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build_citeproc:
    name: Build citeproc
    runs-on: ubuntu-latest
    env:
      CITEPROC_VERSION: '0.7'
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          cabal-version: 'latest'
      - name: Fetch and build citeproc
        run: wget https://github.com/jgm/citeproc/archive/refs/tags/$CITEPROC_VERSION.tar.gz && tar xzf $CITEPROC_VERSION.tar.gz && cd citeproc-$CITEPROC_VERSION && mkdir -p $(pwd)/../dist && cabal install -fexecutable --install-method=copy --installdir=$(pwd)/../dist
      - uses: actions/upload-artifact@v3
        with:
          name: citeproc
          path: dist/citeproc
  build_image:
    name: Build docker image
    needs: build_citeproc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: citeproc
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: thelurps/pandoc:${{github.ref_name}}
  test:
    name: Test docker image
    needs: build_image
    runs-on: ubuntu-latest
    container: thelurps/pandoc:${{github.ref_name}}
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Render
        run: |
          make README-$VERSION.pdf
          TEMPLATE="./eisvogel-template/eisvogel.tex" make eisvogel-$VERSION.pdf
          TO="beamer" make beamer-$VERSION.pdf
      - uses: actions/upload-artifact@master
        with:
          name: 'rendered_pdf-${{ env.VERSION }}'
          path: '*-${{ env.VERSION }}.pdf'
