name: Release

on:
  push:
    branches:
      - 'latest'
      - 'testing'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thelurps/pandoc:${{github.ref_name}}
  test:
    needs: build
    runs-on: ubuntu-latest
    container: thelurps/pandoc:${{github.ref_name}}
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: make all
      - uses: actions/upload-artifact@master
        with:
          name: 'rendered_pdf-${{ env.VERSION }}'
          path: 'README-${{ env.VERSION }}.pdf'
