name: Release

on:
  push:
    branches:
      - 'latest'
      - 'testing'
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build_citeproc:
    runs-on: ubuntu-latest
    env:
      CITEPROC_VERSION: '0.7'
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          cabal-version: 'latest'
      - run: wget https://github.com/jgm/citeproc/archive/refs/tags/$CITEPROC_VERSION.tar.gz && tar xzf $CITEPROC_VERSION.tar.gz -C /tmp && cd /tmp/citeproc-$CITEPROC_VERSION && cabal install -fexecutable 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thelurps/pandoc:${{github.ref_name}}
  test:
    needs: build
    runs-on: ubuntu-latest
    container: thelurps/pandoc:${{github.ref_name}}
    env:
      VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: make all
      - uses: actions/upload-artifact@master
        with:
          name: 'rendered_pdf-${{ env.VERSION }}'
          path: '*-${{ env.VERSION }}.pdf'
